name: Continue building macOS binaries of Helium

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      os:
        required: true
        type: string
    outputs:
      status:
        value: ${{ jobs.build_job.outputs.status }}

jobs:
  build_job:
    name: Resuming Building Helium for macOS
    runs-on: ${{ inputs.os }}
    outputs:
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/prepare-environment

      - name: Get previous logs
        uses: actions/download-artifact@v4
        with:
          name: github_build_logs_${{ inputs.arch }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: github_build_artifact_${{ inputs.arch }}

      - name: Unpack archive of build
        run: ./github_unpack_archive.sh

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ inputs.arch }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ inputs.arch }}-
            ccache-${{ runner.os }}-

      - uses: ./.github/actions/do-build
        id: build
        with:
          arch: ${{ inputs.arch }}
          os: ${{ inputs.os }}
          MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          PROD_MACOS_SPECIAL_ENTITLEMENTS_PROFILE_B64: ${{ secrets.PROD_MACOS_SPECIAL_ENTITLEMENTS_PROFILE_B64 }}

      - name: Save ccache
        uses: actions/cache/save@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ inputs.arch }}-${{ github.run_id }}
