name: Helium Build Diagnostics

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
      fail-fast: false

    steps:
      - name: Print Image and System Info
        run: |
          echo "== OS Version =="
          sw_vers
          echo "== Kernel Version =="
          uname -a
          echo "== Image Timestamp =="
          ls -la /etc | grep runner-release || echo "runner-release info not found"
          echo "== CPU Info =="
          sysctl -n machdep.cpu.brand_string
          echo "== Logical CPU Count =="
          sysctl -n hw.logicalcpu
          echo "== Memory Info =="
          vm_stat

      - name: Check Disk Space (Before Build)
        run: df -h /

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Build Tools
        run: |
          brew update
          brew install cmake ninja

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja

      - name: Start Build Timer
        run: echo "Build started at: $(date)"

      - name: Build Project with Timer
        run: |
          cd build
          START=$(date +%s)
          cmake --build . -j$(sysctl -n hw.logicalcpu)
          END=$(date +%s)
          echo "Build completed at: $(date)"
          echo "Build Duration: $((END - START)) seconds"

      - name: Check Disk Space (After Build)
        run: df -h /

      - name: Upload Build Directory (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}
          path: build/
